version: '3'

services:
  database:
    image: postgres
    container_name: selpe-sales-pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
      # POSTGRES_SCHEMA: 'docker'
      POSTGRES_DB: 'queries_challenge'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
